### ISSUE TITLE
How do I add scss to this structure?

### ISSUE THREAD

**Issue by yunusunver** [saltyshiomix/rollup-typescript-react-starter#1]
Although I did a lot of research, I was unable to add scss. Can you help me?

**Comment by saltyshiomix** [comment]
@yunusunver 

Sure.

Could you try the latest master?

**Comment by yunusunver** [comment]
thanks its worked , I want to build a structure like this;

<img width="115" alt="Ekran Alıntısı" src="https://user-images.githubusercontent.com/24482512/76080145-5355b080-5fb7-11ea-82aa-0eb607754c03.PNG">


But import './app.scss'  I don't want to use it like this. I want to see the scss file in the same folder automatically. Is this possible?
